# Generated by Django 3.0.6 on 2020-07-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_framework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
