# Generated by Django 3.0.6 on 2020-07-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_framework', '0003_blacklistedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='user',
            field=models.IntegerField(max_length=100),
        ),
    ]
