# Generated by Django 3.0.6 on 2020-07-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_framework', '0004_auto_20200730_1335'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blacklistedtoken',
            unique_together=set(),
        ),
    ]
