# Generated by Django 3.0.6 on 2020-07-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_framework', '0007_auto_20200730_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklistedtoken',
            name='user',
        ),
        migrations.AddField(
            model_name='blacklistedtoken',
            name='user_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
